name: Clone
on:
  # kick off the job on demand
  workflow_dispatch:
  # and run on a schedule every 12 hours
  schedule:
    - cron: "* */12 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: andrewthetechie/gha-clone-releases@latest
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          src_repo: jersonreyes/LightBridge
